base: "../base.yml"
model:
  embed_dim: 192
  atten_dim: 192
  depth: 12
  num_heads: 3
  mlp_dim: 768
  attention_scale: 8.0
augmentation:
  random_erasing: 0.05
  color_jitter: False
  three_aug: False
checkpoint: "checkpoints/scratch/tiny_ml.pth"

