base: "../base.yml"
model:
  embed_dim: 192
  atten_dim: 192
  depth: 24
  num_heads: 3
  num_groups: 12
  mlp_dim: 768
  attention_scale: 8.0
  drop_path: 0.05
training:
  batch_size: 2048
  mask_scale: 4.0
checkpoint: "checkpoints/scratch/small_tall_ml.pth"

