base: "../regnet_y_16gf_teacher_base.yml"
model:
  embed_dim: 768
  atten_dim: 768
  depth: 12
  num_heads: 12
  num_groups: 12
  mlp_dim: 3072
  attention_scale: 0.0
  drop_path: 0.2
training:
  hard_labels: True
  batch_size: 1024
checkpoint: "checkpoints/distil/regnet_y_16gf/base_hard.pth"

