base: "../regnet_y_16gf_teacher_base.yml"
model:
  embed_dim: 192
  atten_dim: 192
  depth: 24
  num_heads: 3
  mlp_dim: 768
  attention_scale: 8.0
  drop_path: 0.05
training:
  mask_scale: 8.0
checkpoint: "checkpoints/distil/regnet_y_16gf/small_tall_ml.pth"

