base: "../base.yml"
model:
  image_size: 448
  embed_dim: 192
  atten_dim: 192
  depth: 12
  num_heads: 3
  num_groups: 12
  mlp_dim: 768
  attention_scale: 8.0
  ffn_groups: 12
  use_distil_token: False
training:
  batch_size: 1024
  epochs: 100
  warmup_epochs: 5
  cooldown_epochs: 10
  lr: 0.0005
augmentation:
  resize: 464
  crop: 448
  random_erasing: 0.05
  color_jitter: False
  three_aug: False
checkpoint: "checkpoints/ft_448/tiny_ml_g12_448.pth"

